version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: db
    volumes:
      - ./redis_conf/redis.conf:/etc/redis/redis.conf
      - ./data:/data
      - ./redis_log:/redis_log
    entrypoint: redis-server --appendonly yes
  nginx:
    image: "nginx:alpine"
    restart: always
    container_name: ng
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - ./nginx_log/:/var/log/nginx
  app:
    build: ./app
    volumes:
      - ./app:/var/www/app
    expose:
      - 5000
    environment:
      - REDIS_URL=redis://db
      - NODE_ENV=development
      - PORT=5000
    command:
      sh -c 'npm i && node server.js'
